[build-system]
requires = ["setuptools>=42","setuptools<=66","setuptools_scm[toml]>=3.4","setuptools_scm[toml]<=7.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/BTVNanoCommissioning/version.py"