def get_variables():
    vardict = {
        "JetSVs_chi2": {
            "displayname": "SV $\\chi^2$",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 22,
            "manual_ranges": [-1, 10],
            "inputVar_units": None,
        },
        "JetSVs_costhetasvpv": {
            "displayname": "Cosine of the angle cos(θ) between the SV and the PV",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 40,
            "manual_ranges": [-2.0, 2.0],
            "inputVar_units": None,
        },
        "JetSVs_d3d": {
            "displayname": "3D distance between SV and PV",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 2000,
            "manual_ranges": [0.0, 200.0],
            "inputVar_units": "mm",
        },
        "JetSVs_d3dsig": {
            "displayname": "3D flight distance significance of the SV",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 200,
            "manual_ranges": [0.0, 200.0],
            "inputVar_units": None,
        },
        "JetSVs_dxy": {
            "displayname": "Transverse (2D) flight distance of the SV",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 1000,
            "manual_ranges": [0.0, 100.0],
            "inputVar_units": "mm",
        },
        "JetSVs_dxysig": {
            "displayname": "Transverse (2D) flight distance significance of the SV",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 200,
            "manual_ranges": [0.0, 200.0],
            "inputVar_units": None,
        },
        "JetSVs_enration": {
            "displayname": "energy relative to parent jet [GeV]",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 100,
            "manual_ranges": [0.0, 10.0],
            "inputVar_units": None,
        },
        "JetSVs_mass": {
            "displayname": "invariant mass of the secondary vertex [GeV]",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 100,
            "manual_ranges": [0.0, 10.0],
            "inputVar_units": None,
        },
        "JetSVs_normchi2": {
            "displayname": "Normalized $\\chi^2$ of the SV",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 30,
            "manual_ranges": [0.0, 30.0],
            "inputVar_units": None,
        },
        "JetSVs_ntracks": {
            "displayname": "Number of tracks associated to SV",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 30,
            "manual_ranges": [0.0, 30.0],
            "inputVar_units": None,
        },
        "JetSVs_phirel": {
            "displayname": "DeltaPhi(SV, Jet)",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 200,
            "manual_ranges": [-1.0, 1.0],
            "inputVar_units": None,
        },
        "JetSVs_pt": {
            "displayname": "SV $p_T$",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 200,
            "manual_ranges": [0.0, 200.0],
            "inputVar_units": "[GeV]",
        },
        "JetSVs_ptrel": {
            "displayname": "SV $p_T$ relative to parent jet",
            "ylabel_text": "entries",
            "format_unit": "2f",
            "format_unit_digits": 2,
            "bins": 10,
            "manual_ranges": [0.0, 10.0],
            "inputVar_units": None,
        },
    }

    return vardict
